### PR TITLE
CORE-1945: Set Content-Type for requests

### PR DESCRIPTION
**Pull request by kare**
Including POST request with 0 body length.

### CODE REVIEW

**Comment by hpihkala** [comment]
Note failing tests!

**Comment by timoxley** [comment]
the failing test is likely the original bug I noticed i.e. it's ignoring the passed in id and returning all items, I'm guessing a PR needs to be merged into the engine before this will pass here? e.g. https://github.com/streamr-dev/engine-and-editor/pull/795 ?

**Comment by hpihkala** [comment]
So @kare could you confirm if this is the case: the tests of this PR depend on https://github.com/streamr-dev/engine-and-editor/pull/795, and vice versa?

**Comment by kare** [comment]
@hpihkala @timoxley Yes, Engine requires this for REST API tests to pass and vice versa.

**Pull request merged**
