### PR TITLE
Fix DU2 test

### PR DESCRIPTION
**Pull request by teogeb**
Create a product in backend so that E&E can analyze the DU version.

That change doesn't solve the problem. Maybe there is some conflict in environment config?

Stacktrace in E&E:
`java.lang.IndexOutOfBoundsException: Index: 0
	at java.util.Collections$EmptyList.get(Collections.java:4456)
	at com.streamr.client.dataunion.contracts.DataUnionSidechain$42.call(DataUnionSidechain.java:647)
	at com.streamr.client.dataunion.contracts.DataUnionSidechain$42.call(DataUnionSidechain.java:642)
	at org.web3j.protocol.core.RemoteCall.send(RemoteCall.java:42)
	at com.streamr.client.dataunion.DataUnion.isMemberActive(DataUnion.java:243)
	at com.unifina.service.DataUnionJoinRequestService.isMemberActive(DataUnionJoinRequestService.groovy:43)
	at com.unifina.service.DataUnionJoinRequestService.onApproveJoinRequest(DataUnionJoinRequestService.groovy:83)
	at com.unifina.service.DataUnionJoinRequestService.create(DataUnionJoinRequestService.groovy:188)
	at com.unifina.controller.DataUnionJoinRequestApiController.save(DataUnionJoinRequestApiController.groovy:38)
	at com.brandseye.cors.CorsFilter.doFilter(CorsFilter.java:100)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)`

### CODE REVIEW

**Comment by jtakalai** [comment]
not entirely apparent why product is needed for analyzing DU version

**Comment by bapilcom** [comment]
@jtakalai Product contains the information about the DU version, see https://linear.app/streamr/issue/BACK-29/join-request-endpoints-should-support-v2-data-unions

**Comment by teogeb** [comment]
> not entirely apparent why product is needed for analyzing DU version

@jtakalai Product contains the information about the DU version, see https://linear.app/streamr/issue/BACK-29/join-request-endpoints-should-support-v2-data-unions

**Review by kare — APPROVED** [review]
LGTM

**Pull request merged**
