### PR TITLE
CORE-1707: Fix unauthenticated mode

### PR DESCRIPTION
**Pull request by harbu**
Fix bug in which streamr-client asks E&E for userInfo, i.e. `GET https://www.streamr.com/api/v1/users/me`, even if user has provided no api key.

### CODE REVIEW

**Comment by harbu** [comment]
Thank you @mthambipillai for fixing tests! 👍

**Comment by harbu** [comment]
@hpihkala Not sure if your comment was referring to fixing the existing tests or writing new ones. If the latter, I wasn't planning on writing new ones for this change. Is there some specific scenario you think should be tested here?

**Comment by harbu** [comment]
I'm gonna land this now because this is blocking my work on broker.

**Comment by hpihkala** [comment]
Sorry, what I meant was that a test should be added that would have caught the original issue. (It was a pretty severe bug, surprised it wasn’t caught by any tests).

**Pull request merged**
