### PR TITLE
types(dataunion): Transfer amount to specific member

### PR DESCRIPTION
**Pull request by aseyfpour**
types(dataunion): Transfer amount to a specific member

Added transferToMemberInContract to dataunion

Signed-off-by: AliReza Seyfpour <a.seyfpour@gmail.com>

### CODE REVIEW

**Comment by timoxley** [comment]
@aseyfpour great work, thanks for this, I'm pinging the right people to review.

**Review by jtakalai — CHANGES_REQUESTED** [review]
Code looks good, but it needs a test. Would you like to try writing one? I can also help over a video call, or do it myself later.

**Comment by isentropy** [comment]
looks fine. I prefer a test too.

**Comment by aseyfpour** [comment]
Thanks, sorry for the delay. I added an integration test but I wasn't able to run it locally (I used some different providers but nothing changed) so I used your ci to check the result. I think the code is right but don't know why it still failed. It fails on join request, it receives error 500. I appreciate any help on this.

**Comment by aseyfpour** [comment]
@jtakalai 

Thanks for your feedback and sorry for the delay and lots of commits. I added an integration test but I didn't know how to run it. I tried with different providers but it wasn't successful. Also, I didn't find any documentation or tutorial about how to run the tests, so I used git CI to handle this. Sorry about that. 
I think it is ready to be reviewed again.

**Review by jtakalai — APPROVED** [review]
Good test, great work!

**Pull request merged**
